---
redis:
  service_name: my-redis
  service_id: 12345abcde
  shared_vm_plan_id: id-for-shared-vm-plan
  host: example.com
  data_directory: /tmp/redis/data/directory
  pidfile_directory: /tmp/redis/pidfiles
  log_directory: /tmp/redis/log/directory
  redis_conf_path: /tmp/to/redis/config.conf
  process_check_interval: 5
  start_redis_timeout: 3
  service_instance_limit: 3
  backup:
    endpoint_url: http://s3url.com
    bucket_name: redis-backups
    access_key_id: ABCDEABCDEABCDEABCDE
    secret_access_key: ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE
    s3_region: france
    path: /home
    bg_save_timeout: 600
auth:
  username: admin
  password: secret

backend_host: localhost
backend_port: 3000
agent_port: 1234

monit_executable_path: /some/path/to/monit
redis_server_executable_path: /some/path/to/redis-server

consistency_check_interval_seconds: 123
